# Copyright 2019 Viasat, Inc.
# Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License").
# You may not use this file except in compliance with the License.
# A copy of the License is located at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# or in the "license" file accompanying this file. This file is distributed
# on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
# express or implied. See the License for the specific language governing
# permissions and limitations under the License.

# @formatter:off
{{- if .Values.kibana.enabled }}
apiVersion: v1
kind: Service
metadata:
  annotations:
{{ toYaml .Values.kibana.service.annotations | indent 4 }}
  labels:
{{ include "opendistro-es.labels.standard" . | indent 4 }}
    role: kibana
  name: {{ template "opendistro-es.fullname" . }}-kibana-svc
spec:
  ports:
  - name: kibana-svc
    port: {{ .Values.kibana.externalPort }}
    targetPort: {{ .Values.kibana.port }}
  selector:
    role: kibana
  type: {{ .Values.kibana.service.type }}
{{- end }}
