# Copyright 2019 Viasat, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License").
# You may not use this file except in compliance with the License.
# A copy of the License is located at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# or in the "license" file accompanying this file. This file is distributed
# on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
# express or implied. See the License for the specific language governing
# permissions and limitations under the License.

# @formatter:off
{{- if and .Values.elasticsearch.data.podDisruptionBudget.enabled .Values.elasticsearch.data.enabled .Values.elasticsearch.data.dedicatedPod.enabled }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ template "opendistro-es.fullname" . }}-data-pdb
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "opendistro-es.labels.standard" . | indent 4 }}
spec:
{{- if .Values.elasticsearch.data.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.elasticsearch.data.podDisruptionBudget.minAvailable }}
{{- end }}
{{- if .Values.elasticsearch.data.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.elasticsearch.data.podDisruptionBudget.maxUnavailable }}
{{- end }}
  selector:
    matchLabels:
      app: {{ template "opendistro-es.fullname" . }}
      role: data
{{- end }}
