# Copyright 2019 Viasat, Inc.
# Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License").
# You may not use this file except in compliance with the License.
# A copy of the License is located at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# or in the "license" file accompanying this file. This file is distributed
# on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
# express or implied. See the License for the specific language governing
# permissions and limitations under the License.

# @formatter:off
kind: Service
apiVersion: v1
metadata:
  annotations:
{{ toYaml .Values.elasticsearch.client.service.annotations | indent 4 }}
  labels:
{{ include "opendistro-es.labels.standard" . | indent 4 }}
    role: client
  name: {{ template "opendistro-es.fullname" . }}-client-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: http
      port: 9200
    - name: transport
      port: 9300
    - name: metrics
      port: 9600
    - name: rca
      port: 9650
  selector:
  {{- if .Values.elasticsearch.client.dedicatedPod.enabled }}
    role: client
  {{- else }}
    role: master
  {{- end }}
  type: {{ .Values.elasticsearch.client.service.type }}
