name: Standalone Vulnerability Scan

# Make sure to pass the BRANCH name and GIT Repo name as client_payload in the dispatch event
# Example: client_payload: { "branch": "development", "repo": "index-management" }
# Example: client_payload: { "branch": "master", "repo": "index-management" }

on:
  repository_dispatch:
    types: [check-vulnerability-standalone]

jobs:
  whitesource-vulnerability-scan:
    name: WhiteSource Vulnerability Scan
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        java: [11]
    steps:
      - uses: actions/checkout@v1
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Vulnerability Scan
        id: vulnerability_scan
        env:
          wss_apikey: ${{ secrets.WSS_API_KEY }}
        run: |
          export PATH=$JAVA_HOME:$PATH
          cd standalone-tools ; ls -ltr 
          gradle -v; mvn -v ; npm -v; yarn -v
          branch=${{github.event.client_payload.branch}}
          repo=${{github.event.client_payload.repo}}
          git clone --branch $branch --single-branch https://github.com/opendistro-for-elasticsearch/$repo.git
          wget -q https://github.com/whitesource/unified-agent-distribution/releases/latest/download/wss-unified-agent.jar
          ls -ltr
          echo 'project_url<<EOF' >> $GITHUB_ENV
          java -jar wss-unified-agent.jar -c wss-unified-agent.config -d $repo -apiKey $wss_apikey -product ODFE -project $repo | grep "Project name" | sed 's/^.\{,41\}//' >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
          cat whitesource/*/*
      - name: WhiteSource URL
        run: echo "${{env.project_url}}"

