name: Standalone Vulnerability Scan

on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'GIT repo to be scanned'
        required: true
        default: 'opendistro-build'
      branch:
        description: 'GIT Branch to be used for scanning'
        required: true
        default: 'master'
#  repository_dispatch:
#    types: [check-vulnerability-standalone]

jobs:
  whitesource-vulnerability-scan:
    name: WhiteSource Vulnerability Scan
    runs-on: [ubuntu-18.04]
    strategy:
      fail-fast: false
      matrix:
        java: [11]
    steps:
      - uses: actions/checkout@v1
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Vulnerability Scan
        id: vulnerability_scan
        env:
          wss_apikey: ${{ secrets.WSS_API_KEY }}
        run: |
          export PATH=$JAVA_HOME:$PATH
          cd standalone-tools ; ls -ltr 
          #sudo yum install -y maven
          #wget -q https://services.gradle.org/distributions/gradle-6.7-bin.zip
          #sudo mkdir /opt/gradle
          #sudo unzip -d /opt/gradle gradle-6.7-bin.zip
          #wget -qO - https://rpm.nodesource.com/setup_14.x | sudo bash -
          #sudo yum install -y nodejs
          #wget -qO - https://dl.yarnpkg.com/rpm/yarn.repo | sudo tee /etc/yum.repos.d/yarn.repo
          #sudo rpm --import https://dl.yarnpkg.com/rpm/pubkey.gpg
          #sudo yum install yarn -y
          #export PATH=$PATH:/opt/gradle/gradle-6.7/bin
          gradle -v; mvn -v ; npm -v; yarn -v
          wget -q https://github.com/whitesource/unified-agent-distribution/releases/latest/download/wss-unified-agent.jar
          #branch = $1
          #repo = $2
          git clone --depth 1 --branch ${{ github.event.inputs.branch }} https://github.com/opendistro-for-elasticsearch/index-management.git
          ls -ltr
          #java -jar wss-unified-agent.jar -c wss-unified-agent.config -d index-management -apiKey $wss_apikey -product ODFE -project index-management
          #cat whitesource/*/*
