name: Build Windows Exe using TAR artifacts

on:
  push:
    branches: 
      - rish1397-patch-1
jobs:
  build-es-artifacts:
    name: Build ES Artifacts
    runs-on: ubuntu-latest
    container:
      image: opendistroforelasticsearch/multijava08101112-git:v1

    steps:
    - uses: actions/checkout@v1
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Build tar
      run: |
        #!/bin/bash -x
        set -e
        set -u
        #export JAVA_HOME=/openjdk12
        #export PATH=$JAVA_HOME:$PATH
        cd elasticsearch/linux_distributions
        #./opendistro-tar-build.sh
        echo ********the path is*********
        pwd
        #cd elasticsearch/linux_distributions
        
    - name: Build Windows
      run: |
        echo `pwd`
        
