name: Sync Deb artifacts to Prod

on: 
  repository_dispatch:
    types: [prod-sync-deb]

jobs:
  Sync-Deb-Prod:
    runs-on: ubuntu-18.04
    container: 
      image: opendistroforelasticsearch/base-ubuntu
    name: Sync Deb Artifacts to Prod
    steps:
      - uses: actions/checkout@v1
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Required Packages
        run: |
          apt-get update
          apt-get install sudo -y
          ./release-tools/scripts/required_packages.sh

      - name: (NEW) (PROD) Sync Deb Artifacts
        run: ./elasticsearch/linux_distributions/deb-signing.sh passphrase x64 prod-sync

