name: Sync Deb artifacts to Prod

on: 
  repository_dispatch:
    types: [prod-sync-deb]

jobs:
  Sync-Deb-Prod:
    runs-on: ubuntu-18.04
    container: 
      image: opendistroforelasticsearch/base-ubuntu
    name: Sync Deb Artifacts to Prod
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          
      - name: Sign and Sync
        env:
          passphrase: ${{ secrets.PASSPHRASE }}
        run: |
          
          echo "deb http://repo.aptly.info/ squeeze main" | sudo tee -a /etc/apt/sources.list.d/aptly.list
          sudo apt-get install -y gnupg1
          sudo apt install -y gpgv1
          alias gpg=gpg1
          wget -qO - https://www.aptly.info/pubkey.txt | sudo apt-key add -
 
          sudo apt-get update -y
          sudo apt-get install -y aptly
          aws s3 cp s3://opendistro-docs/github-actions/pgp-public-key .
          aws s3 cp s3://opendistro-docs/github-actions/pgp-private-key .
 
          aptly repo create -distribution=stable -component=main odfe-release
 
          mkdir -p downloads/debs
          aws s3 sync s3://artifacts.opendistroforelasticsearch.amazon.com/downloads/debs downloads/debs
          aptly repo add odfe-release downloads
 
          aptly repo show -with-packages odfe-release
          aptly snapshot create opendistroforelasticsearch from repo odfe-release
          aptly snapshot list
 
          gpg --import pgp-public-key
          gpg --allow-secret-key-import --import pgp-private-key
          echo "Printing Secret List"
          ls -ltr ~/.gnupg/
          gpg --list-secret
 
          aptly publish snapshot -batch=true -passphrase=$passphrase opendistroforelasticsearch
 
          aws s3 sync ~/.aptly/public/ s3://artifacts.opendistroforelasticsearch.amazon.com/apt
 
          aws cloudfront create-invalidation --distribution-id E1VG5HMIWI4SA2 --paths "/apt/*"
        
