name: Sync RPM artifacts to Production

on:
  repository_dispatch:
    types: [prod-sync-rpm]
  
jobs:
  signing-artifacts:   
    name: Sign Yum
    runs-on: [ubuntu-16.04]
    container: 
      image: amazonlinux
    steps:
      - uses: actions/checkout@v1
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: Required Packages
        run: ./release-tools/scripts/required_packages.sh

      - name: (New) (PROD) Sync artifacts from staging to prod repo
        run: ./elasticsearch/linux_distributions/rpm-signing.sh passphrase prod-sync


