name: Sync tar artifacts to Prod

on: 
  repository_dispatch:
    types: [release-sync-tar]

jobs:
  Sync-Tarball-Prod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Getting OD version
        run: |
          cd elasticsearch/bin
          OD_VERSION=`./version-info --od`
          echo "::set-env name=od_version::$OD_VERSION"
    
      - name: Moving tar artifacts from staging to prod
        run: |
          aws s3 cp s3://artifacts.opendistroforelasticsearch.amazon.com/downloads/tarball/opendistro-elasticsearch/opendistroforelasticsearch-$od_version* \
          s3://artifacts.opendistroforelasticsearch.amazon.com/tarball/opendistro-elasticsearch/

          aws s3 cp s3://artifacts.opendistroforelasticsearch.amazon.com/downloads/tarball/opendistroforelasticsearch-kibana/opendistroforelasticsearch-kibana-$od_version* \
          s3://artifacts.opendistroforelasticsearch.amazon.com/tarball/opendistroforelasticsearch-kibana/

          aws cloudfront create-invalidation --distribution-id E1VG5HMIWI4SA2 --paths "/tarball/*"
