name: Build ES Docker

on: 
  #schedule:
  #  - cron: '30 10 * * *'
  #repository_dispatch:
  #  types: [staging-build-docker]
  # push:
  #   branches: [sreekarj_jdk15]

jobs:
  Test-KNN-NoSec:
   #needs: [build-es-docker]
    runs-on: [ubuntu-18.04]
    name: Test-KNN-NoSec
    strategy:
      fail-fast: false        
      matrix:
        java: [14, 15]
    steps:
      - uses: actions/checkout@v1
      - name: Retrieve plugin tags 
        run:  echo ::set-env name=p_tag_knn::$(.github/scripts/plugin_tag.sh opendistro-for-elasticsearch/k-NN)
      - uses: actions/checkout@v1
        with:
          repository: opendistro-for-elasticsearch/k-NN
          ref: ${{env.p_tag_knn}}
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: IT
        run: |
          .github/scripts/setup_runners_service.sh docker --es-nosec
          export PATH=$JAVA_HOME:$PATH; cd $GITHUB_WORKSPACE/../k-NN; pwd
          ./gradlew integTest -Dtests.rest.cluster=localhost:9200 -Dtests.cluster=localhost:9200 -Dtests.clustername=es-integrationtest
   
