name: Test TAR Artifacts X64

on:
#  schedule:
#    - cron: '0 11 * * *'
  repository_dispatch:
    types: [staging-test-tar-x64]
  push:
    branches: [sreekarj_alerting]

jobs:
  Test-Alerting-NoSec:
    runs-on: ubuntu-18.04
    name: Test-Alerting-NoSec
    strategy:
      fail-fast: false
      matrix:
        java: [14]
    steps:
      - name: Set up AWS Cred
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_STAGING_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_STAGING_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - uses: actions/checkout@v1
      - name: Required Packages
        run: ./release-tools/scripts/required_packages.sh
      - name: Retrieve plugin tags
        run:  echo "p_tag_alerting=$(release-tools/scripts/plugin_tag.sh opendistro-for-elasticsearch/alerting)" >> $GITHUB_ENV
      - name: Checkout Alerting
        uses: actions/checkout@v1
        with:
          repository: opendistro-for-elasticsearch/alerting
          ref: ${{env.p_tag_alerting}}
      - name: IT
        run: |
          ./release-tools/scripts/setup_runners_service.sh zip --es-nosec
          echo "opendistro.destination.host.deny_list: [\"10.0.0.0/8\", \"127.0.0.1\"]" >> \
          ./release-tools/scripts/odfe-testing/opendistroforelasticsearch*/config/elasticsearch.yml
          cat ./release-tools/scripts/odfe-testing/opendistroforelasticsearch*/config/elasticsearch.yml
          export PATH=$JAVA_HOME:$PATH; cd $GITHUB_WORKSPACE/../alerting/alerting; pwd
          ../gradlew integTest -Dtests.rest.cluster=localhost:9200 -Dtests.cluster=localhost:9200 -Dtests.clustername=es-integrationtest

  
  Test-ALERTING:
    runs-on: ubuntu-18.04
    name: Test-ALERTING
    strategy:
      fail-fast: false
      matrix:
        java: [14]
    steps:
      - uses: actions/checkout@v1
      - name: Set up AWS Cred
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_STAGING_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_STAGING_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Required Packages
        run: ./release-tools/scripts/required_packages.sh
      - name: Retrieve plugin tags 
        run:  echo "p_tag_alerting=$(release-tools/scripts/plugin_tag.sh opendistro-for-elasticsearch/alerting)" >> $GITHUB_ENV

      - uses: actions/checkout@v1
        with:
          repository: opendistro-for-elasticsearch/alerting
          ref: ${{env.p_tag_alerting}}

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: IT
        run: |
          ./release-tools/scripts/setup_runners_service.sh zip --es
          ls -ltr

          export PATH=$JAVA_HOME:$PATH; cd $GITHUB_WORKSPACE/../alerting/alerting; pwd
          ls -ltr
          ../gradlew integTest -Dtests.rest.cluster=localhost:9200 -Dtests.cluster=localhost:9200 -Dtests.clustername=es-integrationtest -Dhttps=true -Duser=admin -Dpassword=admin -Dsecurity=true
               
