name: Process Debian Artifacts

on: 
  #schedule:
  #  - cron: '0 10 * * *'
  repository_dispatch:
    types: [staging-build-deb-temp]
  push:
    branches: [opendistro-infra-issues-237-1]

jobs:
  build-es-artifacts:
    name: Build ES Artifacts
    runs-on: ubuntu-18.04
    container:
      image: opendistroforelasticsearch/multijava08101112-git:v1
    steps:
      - uses: actions/checkout@v1
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Build deb
        run: |
          #!/bin/bash -x
          set -e
          set -u
          apt update -y
          apt install jq python -y
          export JAVA_HOME=/openjdk12
          export PATH=$JAVA_HOME:$PATH
          cd elasticsearch/linux_distributions
          ./gradlew buildDeb --console=plain -Dbuild.snapshot=false -b ./build.gradle --scan
          ls -ltr build/distributions/*.deb
          deb_artifact=`ls build/distributions/*.deb`
          dpkg -i $deb_artifact

          #aws s3 cp $deb_artifact s3://artifacts.opendistroforelasticsearch.amazon.com/downloads/debs/opendistro-elasticsearch/
          #aws cloudfront create-invalidation --distribution-id E1VG5HMIWI4SA2 --paths "/downloads/*"
          #echo "DEB creation for ES completed"

