name: Build Windows Exe using tar artifacts

on:
  #schedule:
  #  - cron: '30 10 * * *'
  #repository_dispatch:
  #  types: [staging-build-windows]
  push: 
    branches: [sreekarj_jdk15]
jobs:
  Test-ISM-NoSec:
    needs: [build-es-artifacts, build-kibana-artifacts]
    runs-on: windows-latest
    name: Test-ISM-NoSec
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v1
      - name: Retrieve plugin tags
        run: echo ::set-env name=p_tag_ism::$(.github/scripts/plugin_tag.sh opendistro-for-elasticsearch/index-management)
        shell: bash
      - uses: actions/checkout@v1
        with:
           repository: opendistro-for-elasticsearch/index-management
           ref: ${{env.p_tag_ism}}  
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Set Up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: 14, 15
       
      - name: RUN ES and ISM IntegTest
        run: |
          .github\scripts\setup_runners_service_windows.ps1 --es-nosec
          $ErrorActionPreference = 'SilentlyContinue'
          echo running tests
          cd ..\index-management
          dir
          ./gradlew.bat integTest -D tests.rest.cluster=localhost:9200 -D tests.cluster=localhost:9200 -D tests.clustername=es-integrationtest --stacktrace 
