name: Staging Copy Artifacts

on:
#  schedule:
#    - cron: '0 9 * * *' 
  repository_dispatch:
    types: [staging-copy-artifacts]


jobs:
  Staging-Copy-Artifacts:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_STAGING_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_STAGING_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Install python packages
        run: |
          sudo pip install boto3
          sudo pip install pyyaml
          sudo pip install requests
    
      - name: Moving artifacts from snapshots to release folder
        run: |
          cd release-tools/scripts
          ./staging-copy-artifacts.py ${GITHUB_RUN_ID}
