name: Process TAR Artifacts

on:
  #schedule:
  #  - cron: '0 10 * * *'
  repository_dispatch:
    types: [test-build-tar]

jobs:
  Test-SQL-Plugin-With-Security:
    name: Run SQL Test with Security
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [14]
    steps:
      - name: Set up AWS Cred
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - uses: actions/checkout@v1
      - name: Retrieve plugin tags
        run:  echo ::set-env name=p_tag_sql::$(.github/scripts/plugin_tag.sh opendistro-for-elasticsearch/sql)
      - name: Checkout SQL
        uses: actions/checkout@v1
        with:
          repository: opendistro-for-elasticsearch/sql
          ref: ${{env.p_tag_sql}}
      - name: Run Tests
        run: |
          odfe_version=`./bin/version-info --od`
          echo $odfe_version
          cd ..
          cd opendistro-build/elasticsearch/linux_distributions
          cd ../../..
          aws s3 cp s3://artifacts.opendistroforelasticsearch.amazon.com/downloads/tarball/opendistro-elasticsearch/opendistroforelasticsearch-$odfe_version.tar.gz .
          tar -zxf opendistroforelasticsearch-$odfe_version.tar.gz
          cd opendistroforelasticsearch-$odfe_version
          bash ./plugins/opendistro_security/tools/install_demo_configuration.sh -y -i -s
          sed -i /^node.max_local_storage_nodes/d ./config/elasticsearch.yml
          cat ./config/elasticsearch.yml
          nohup ./opendistro-tar-install.sh &
          sleep 45
          cd ../sql
          ./gradlew integTest -Dtests.rest.cluster=localhost:9200 -Dtests.cluster=localhost:9200 -Dtests.clustername=es-integrationtest
          
      
