name: Build Windows Exe using tar artifacts

on:
  schedule:
    - cron: '0 10 * * *'
  repository_dispatch:
    types: [build-windows]

jobs:
  build-es-artifacts:
    name: Build Windows ES Artifacts
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 14

    - name: Build Windows
      run: |
        set -e
        set -u
        cd elasticsearch/linux_distributions
        chmod 755 opendistro-windows-build.sh
        sh ./opendistro-windows-build.sh
        
  build-kibana-artifacts:
    name: Build Kibana Artifacts
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 14

    - name: Build Kibana
      run: |
        cd kibana/linux_distributions 
        chmod 755 opendistro-windows-kibana-build.sh
        sh ./opendistro-windows-kibana-build.sh
          
  Test-ISM-Plugin:
    needs: [build-es-artifacts, build-kibana-artifacts]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/checkout@v1
        with:
           repository: opendistro-for-elasticsearch/index-management
           ref: master  
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Set Up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: 14
       
      - name: RUN ES and ISM IntegTest
        run: |
          dir
          python -m pip install --upgrade pip
          echo pip3 -version
          pip3 install awscli
          cd elasticsearch\bin\
          dir
          $PACKAGE="opendistroforelasticsearch"
          $OD_VERSION=$(python .\version-info --od)
          $S3_PACKAGE="odfe-"+$OD_VERSION+".zip"
          cd ..\..
          dir
          echo downloading zip from S3 
          aws s3 cp s3://artifacts.opendistroforelasticsearch.amazon.com/downloads/odfe-windows/staging/odfe-window-zip/$S3_PACKAGE .\
          echo unzipping $S3_PACKAGE
          unzip .\$S3_PACKAGE
          dir
          echo "removing security plugin"
          cd $PACKAGE-$OD_VERSION\bin
          .\elasticsearch-plugin.bat remove opendistro_security
          cd ..\..
          echo "Overriding with elasticsearch.yml having no certificates"
          del .\$PACKAGE-$OD_VERSION\config\elasticsearch.yml
          aws s3 cp s3://artifacts.opendistroforelasticsearch.amazon.com/downloads/utils/elasticsearch.yml .\$PACKAGE-$OD_VERSION\config
          echo running es
          nohup .\$PACKAGE-$OD_VERSION\bin\elasticsearch.bat &
          echo Waiting for 2min
          ping -n 120 127.0.0.1 >.\out.txt
          echo running tests
          cd ..\index-management
          dir
          ./gradlew.bat integTest -D tests.rest.cluster=localhost:9200 -D tests.cluster=localhost:9200 --stacktrace          

  Test-Alerting-plugin:
    needs: [build-es-artifacts, build-kibana-artifacts]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/checkout@v1
        with:
           repository: opendistro-for-elasticsearch/alerting
           ref: master  
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Set Up JDK 
        uses: actions/setup-java@v1
        with:
          java-version: 14
        
      - name: RUN ES and Alerting IntegTest
        run: |
          dir
          python -m pip install --upgrade pip
          echo pip3 -version
          pip3 install awscli
          cd elasticsearch\bin\
          $PACKAGE="opendistroforelasticsearch"
          $OD_VERSION=$(python .\version-info --od)
          $S3_PACKAGE="odfe-"+$OD_VERSION+".zip"
          cd ..\..
          dir
          echo downloading zip from S3 
          aws s3 cp s3://artifacts.opendistroforelasticsearch.amazon.com/downloads/odfe-windows/staging/odfe-window-zip/$S3_PACKAGE .\
          echo unzipping $S3_PACKAGE
          unzip .\$S3_PACKAGE
          echo "removing security plugin"
          cd $PACKAGE-$OD_VERSION\bin
          .\elasticsearch-plugin.bat remove opendistro_security
          cd ..\..
          echo "Overriding with elasticsearch.yml having no certificates"
          del .\$PACKAGE-$OD_VERSION\config\elasticsearch.yml
          aws s3 cp s3://artifacts.opendistroforelasticsearch.amazon.com/downloads/utils/elasticsearch.yml .\$PACKAGE-$OD_VERSION\config
          echo running es
          nohup .\$PACKAGE-$OD_VERSION\bin\elasticsearch.bat &
          echo Waiting for 2min
          ping -n 120 127.0.0.1 >.\out.txt
          echo running tests
          cd ..\alerting\alerting
          dir
          ../gradlew.bat integTest -D tests.rest.cluster=localhost:9200 -D tests.cluster=localhost:9200 --stacktrace
