name: Test index management

on:
  push:
    branches: 
      - rish1397-patch-1
      
jobs:
  test:
    name: Run integration test for index-management
    runs-on: [ubuntu-16.04]
    steps:
      - uses: actions/checkout@v1
        with:
          repository: rish1397/index-management
          ref: rish1397-patch-1
          token: ${{ secrets.GitHub_PAT }}
      - uses: actions/setup-java@v1
        with:
          java-version: '11.0.x'
          java-package: jdk
          architecture: x64
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Run Tar
        run: |
          aws s3 cp s3://artifacts.opendistroforelasticsearch.amazon.com/downloads/tarball/opendistro-elasticsearch/opendistroforelasticsearch-1.3.0.tar.gz .
          ls -ltr
          tar -zxf opendistroforelasticsearch-1.3.0.tar.gz
          cd opendistroforelasticsearch-1.3.0
          ls -ltr
          
          nohup ./opendistro-tar-install.sh &
          sleep 1m
          cd ../..
          echo running graddle
          ./index-management/gradlew integTest -Dtests.rest.cluster=localhost:9200 -Dtests.cluster=localhost:9200
          
