# Alert: This workflow will delete "ALL" the ODFE testing cluster stacks
name: Delete testing clusters
on:
  repository_dispatch:
    types: [test-cluster-delete]

jobs:
  Create-Cluster:
    name: Delete Testing cluster
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_STACK_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_STACK_SECRET }}
          aws-region: us-west-2

      - name: Deleting all ODFE clusters
        run: |
            #!/bin/bash
            set -e
            stacks=`aws cloudformation list-stacks --stack-status-filter CREATE_COMPLETE --query 'StackSummaries[*].StackName' --output text`
            echo "#######################################"
            echo $stacks | tr " " "\n"
            echo "#######################################"

            for i in $stacks
            do
                if [[ $i = ODFE-* ]] 
                then
                    echo "Deleting $i stack"
                    aws cloudformation delete-stack --stack-name $i
                    aws cloudformation wait stack-delete-complete --stack-name $i
                    echo "$i stack deleted successfully!!"
                fi
            done
