name: Create testing cluster

# Make sure to pass the distribution type (RPM/DEB/TAR) and security feature (enable, disable) as client_payload in the dispatch event
# Example: client_payload: { "distribution": "rpm", "security": "enable" }
# Example: client_payload: { "distribution": "deb", "security": "disable" }

on:
  repository_dispatch:
    types: [test-cluster-set-up]

jobs:
  Create-Cluster:
    name: Create Testing cluster
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_STACK_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_STACK_SECRET }}
          aws-region: us-west-2

      - name: Creating cluster
        run: |
            #!/bin/bash
            set -e

            distribution_type=`echo ${{github.event.client_payload.distribution}} | tr [:lower:] [:upper:]`
            security=`echo ${{github.event.client_payload.security}} | tr [:lower:] [:upper:]`
            echo $distribution_type $security
            stackName=ODFE-$distribution_type-SECURITY-$security

            existingStacks=`aws cloudformation list-stacks --query 'StackSummaries[*].StackName' --output text`

            for i in $existingStacks
            do
                if [[ $i = $stackName ]]
                then
                    echo "Stack already exists! Deleting the old stack"
                    aws cloudformation delete-stack --stack-name $stackName
                    aws cloudformation wait stack-delete-complete --stack-name $stackName
                    echo "$stackName deleted successfully!!"
                fi
            done
            
            release-tools/scripts/userdata.sh "$distribution_type" "$security"
            ls -ltr

            echo "Creating $stackName stack"

            aws cloudformation create-stack --stack-name $stackName \
            --template-body file://release-tools/templates/odfe-testing-cluster-template.json \
            --parameters ParameterKey=userdata,ParameterValue=$(base64 -w0 userdata_$distribution_type.sh) \
            ParameterKey=distribution,ParameterValue=$distribution_type \
            ParameterKey=security,ParameterValue=$security \
            ParameterKey=vpcId,ParameterValue=${{secrets.VPCID}} \
            ParameterKey=ODFESecurityGroup,ParameterValue=${{secrets.ODFESECURITYGROUP}} \
            ParameterKey=keypair,ParameterValue=${{secrets.AWS_ODFE_TESTING_CLUSTER_KEYPAIR}}

            aws cloudformation wait stack-create-complete --stack-name $stackName
            sleep 60
            echo "################################################################################################"
            echo "Elasticsearch endpoint = `aws elbv2 describe-load-balancers --name ODFE-ES-$distribution_type-SECURITY-$security --query 'LoadBalancers[*].DNSName' --output text`"
            echo "################################################################################################"
            echo "Kibana endpoint = `aws elbv2 describe-load-balancers --name ODFE-KIBANA-$distribution_type-SECURITY-$security --query 'LoadBalancers[*].DNSName' --output text`"
            echo "################################################################################################"
