name: Build Windows Exe using tar artifacts

on:
  #schedule:
  #  - cron: '30 10 * * *'
  repository_dispatch:
    types: [test-build-windows]

jobs:
  Test-AD-plugin-With-Security:
    needs: [build-es-artifacts, build-kibana-artifacts]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - name: Retrieve plugin tags
        run:  echo ::set-env name=p_tag_ad::$(.github/scripts/plugin_tag.sh opendistro-for-elasticsearch/anomaly-detection)
        shell: bash
      - uses: actions/checkout@v1
        with:
           repository: opendistro-for-elasticsearch/anomaly-detection
           ref: ${{env.p_tag_ad}}  
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Set Up JDK 
        uses: actions/setup-java@v1
        with:
          java-version: 14
        
      - name: RUN ES and AD IntegTest
        run: |
          dir
          python -m pip install --upgrade pip
          echo pip3 -version
          pip3 install awscli
          $PACKAGE="opendistroforelasticsearch"
          $OD_VERSION=$(python ./bin/version-info --od)
          $S3_PACKAGE="odfe-"+$OD_VERSION+".zip"
          dir
          echo downloading zip from S3 
          aws s3 cp s3://artifacts.opendistroforelasticsearch.amazon.com/downloads/odfe-windows/staging/odfe-window-zip/$S3_PACKAGE .\
          echo unzipping $S3_PACKAGE
          unzip .\$S3_PACKAGE
          echo running es
          nohup .\$PACKAGE-$OD_VERSION\bin\elasticsearch.bat &
          echo Waiting for 2min
          ping -n 120 127.0.0.1
          echo running tests
          cd ..\anomaly-detection
          dir
          .\gradlew.bat :integTestRunner --tests "com.amazon.opendistroforelasticsearch.ad.rest.*IT" --tests "com.amazon.opendistroforelasticsearch.ad.e2e.*IT" -D tests.rest.cluster=localhost:9200 -D tests.cluster=localhost:9200 -D tests.clustername=es-integrationtest -D https=true -D user=admin -D password=admin --stacktrace
  Test-SQL-plugin:
    needs: [build-es-artifacts, build-kibana-artifacts]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - name: Retrieve plugin tags
        run:  echo ::set-env name=p_tag_sql::$(.github/scripts/plugin_tag.sh  opendistro-for-elasticsearch/sql)
        shell: bash
      - uses: actions/checkout@v1
        with:
           repository: opendistro-for-elasticsearch/sql
           ref: ${{env.p_tag_sql}}  
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Set Up JDK 
        uses: actions/setup-java@v1
        with:
          java-version: 14
        
      - name: RUN ES and SQL IntegTest
        run: |
          dir
          python -m pip install --upgrade pip
          echo pip3 -version
          pip3 install awscli
          $PACKAGE="opendistroforelasticsearch"
          $OD_VERSION=$(python ./bin/version-info --od)
          $S3_PACKAGE="odfe-"+$OD_VERSION+".zip"
          dir
          echo downloading zip from S3 
          aws s3 cp s3://artifacts.opendistroforelasticsearch.amazon.com/downloads/odfe-windows/staging/odfe-window-zip/$S3_PACKAGE .\
          echo unzipping $S3_PACKAGE
          unzip .\$S3_PACKAGE
          echo "removing security plugin"
          cd $PACKAGE-$OD_VERSION\bin
          .\elasticsearch-plugin.bat remove opendistro_security
          cd ..\..
          echo "Overriding with elasticsearch.yml having no certificates"
          del .\$PACKAGE-$OD_VERSION\config\elasticsearch.yml
          aws s3 cp s3://artifacts.opendistroforelasticsearch.amazon.com/downloads/utils/elasticsearch.yml .\$PACKAGE-$OD_VERSION\config
          echo running es
          nohup .\$PACKAGE-$OD_VERSION\bin\elasticsearch.bat &
          echo Waiting for 2min
          ping -n 120 127.0.0.1 
          echo running tests
          cd ..\sql
          dir
          .\gradlew.bat integTest -D tests.rest.cluster=localhost:9200 -D tests.cluster=localhost:9200 -D tests.clustername=es-integrationtest --stacktrace
        
        
  Test-SQL-plugin-With-Security:
    needs: [build-es-artifacts, build-kibana-artifacts]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - name: Retrieve plugin tags
        run:  echo ::set-env name=p_tag_sql::$(.github/scripts/plugin_tag.sh  opendistro-for-elasticsearch/sql)
        shell: bash
      - uses: actions/checkout@v1
        with:
           repository: opendistro-for-elasticsearch/sql
           ref: ${{env.p_tag_sql}}  
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Set Up JDK 
        uses: actions/setup-java@v1
        with:
          java-version: 14
        
      - name: RUN ES and SQL IntegTest
        run: |
          dir
          python -m pip install --upgrade pip
          echo pip3 -version
          pip3 install awscli
          $PACKAGE="opendistroforelasticsearch"
          $OD_VERSION=$(python ./bin/version-info --od)
          $S3_PACKAGE="odfe-"+$OD_VERSION+".zip"
          dir
          echo downloading zip from S3 
          aws s3 cp s3://artifacts.opendistroforelasticsearch.amazon.com/downloads/odfe-windows/staging/odfe-window-zip/$S3_PACKAGE .\
          echo unzipping $S3_PACKAGE
          unzip .\$S3_PACKAGE
          echo "removing useless config"
          findstr /V "node.max_local_storage_nodes" .\$PACKAGE-$OD_VERSION\config\elasticsearch.yml > .\$PACKAGE-$OD_VERSION\config\elasticsearch.yml
          type .\$PACKAGE-$OD_VERSION\config\elasticsearch.yml
          echo running es
          nohup .\$PACKAGE-$OD_VERSION\bin\elasticsearch.bat &
          echo Waiting for 2min
          ping -n 120 127.0.0.1 
          echo running tests
          cd ..\sql
          dir
          .\gradlew.bat integTest -D tests.rest.cluster=localhost:9200 -D tests.cluster=localhost:9200 -D tests.clustername=es-integrationtest -D https=true -D user=admin -D password=admin --stacktrace
